player:
  attributes:
    # life/health
    defence: 1.0
    health: 1.0
    health_regen: 1.0
    # combat attack
    damage: 1.0
    crit_chance: 1.0
    attack_speed: 1.0
    throw_range: 1.0
    refill_speed: 1.0
    potion_swap_speed: 1.0
    # combat survival
    life_steal: 
    # general mobility
    move_speed: 1.0
    jump_height: 1.0
    # inventory
    inventory_slots: 1.0
    potion_ready_slots: 1.0